---
-   name: Install node_exporter
    apt:
        name: prometheus-node-exporter
        state: present
        update_cache: yes

-   name: Enable and start node_exporter
    service:
        name: prometheus-node-exporter
        state: started
        enabled: yes
