---
packages:
    - prometheus
    - prometheus-alertmanager
    - adduser
    - libfontconfig1

grafana_version: "10.4.3"
grafana_admin_user: admin
grafana_admin_password: "admin"
webhook_url: "https://webhook.site/860a1ac0-1835-46ed-8fa1-6916ccfbc60f"
