---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-HAAD23-DV1673-H25-LP2
domain_name: haad23-microblog-old.northeurope.cloudapp.azure.com
app_upstream_host: 172.16.0.8

admin_email: haad23@student.bth.se

vmtags:
    StudentId: haad23


pub_ssh_key_location: '/home/hassan/.ssh/dbwebb.pub'


ansible_ssh_private_key_file: /home/hassan/.ssh/id_rsa

server_user: "deploy"
server_user_pass: "0809" # change me
server_user_groups:
    -   sudo
