
# syntax=docker/dockerfile:1.4

FROM python:3.8-alpine

RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache libffi openssl && \
    adduser -D microblog

WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python -m venv .venv && \
    apk add --no-cache --virtual .build-deps build-base libffi-dev openssl-dev && \
    .venv/bin/pip3 install --no-cache-dir --upgrade pip setuptools wheel && \
    .venv/bin/pip3 install --no-cache-dir -r requirements.txt && \
    apk del .build-deps

ENV FLASK_APP=microblog.py

RUN chmod +x boot.sh && \
    chown -R microblog:microblog /home/microblog

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]