apiVersion: v1
kind: Secret
metadata:
  name: microblog-secrets
  namespace: samra
  labels:
    app.kubernetes.io/name: microblog
    app.kubernetes.io/component: config
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-prod"
  DATABASE_URL: "mysql+pymysql://microblog:password@mysql/microblog"
  MYSQL_PASSWORD: "password"
  MYSQL_ROOT_PASSWORD: "rootpassword"
